/** COMMON */
export const CHANGE_LANGUAGE = "[COMMON] CHANGE_LANGUAGE";
/** MASRER DATA */
export const START_MASTER_GET_ALL = "[MASTER] START_MASTER_GET_ALL";
export const SUCCESS_MASTER_GET_ALL = "[MASTER] SUCCESS_MASTER_GET_ALL";
export const ERROR_MASTER_GET_ALL = "[MASTER] ERROR_MASTER_GET_ALL";
/** REFRESH TOKEN */
export const REFRESH_TOKEN = "[AUTH] REFRESH_TOKEN";
/** SIGN OUT */
export const SIGN_OUT = "[AUTH] SIGN_OUT";
/** SIGN IN */
export const START_SIGN_IN = "[AUTH] START_SIGN_IN";
export const SUCCESS_SIGN_IN = "[AUTH] SUCCESS_SIGN_IN";
export const ERROR_SIGN_IN = "[AUTH] ERROR_SIGN_IN";
/** FORGOT PASSWORD */
export const RESET_FORGOT_PASSWORD = "[AUTH] RESET_FORGOT_PASSWORD";
export const START_FORGOT_PASSWORD = "[AUTH] START_FORGOT_PASSWORD";
export const SUCCESS_FORGOT_PASSWORD = "[AUTH] SUCCESS_FORGOT_PASSWORD";
export const ERROR_FORGOT_PASSWORD = "[AUTH] ERROR_FORGOT_PASSWORD";
/** RESET PASSWORD */
export const RESET_RESET_PASSWORD = "[AUTH] RESET_RESET_PASSWORD";
export const START_TOKEN_PASSWORD = "[AUTH] START_TOKEN_PASSWORD";
export const SUCCESS_TOKEN_PASSWORD = "[AUTH] SUCCESS_TOKEN_PASSWORD";
export const ERROR_TOKEN_PASSWORD = "[AUTH] ERROR_TOKEN_PASSWORD";
export const START_RESET_PASSWORD = "[AUTH] START_RESET_PASSWORD";
export const SUCCESS_RESET_PASSWORD = "[AUTH] SUCCESS_RESET_PASSWORD";
export const ERROR_RESET_PASSWORD = "[AUTH] ERROR_RESET_PASSWORD";
/** APPROVED - ASSETS */
export const START_LIST_ASSETS = "[APPROVED] START_LIST_ASSETS";
export const SUCCESS_LIST_ASSETS = "[APPROVED] SUCCESS_LIST_ASSETS";
export const ERROR_LIST_ASSETS = "[APPROVED] ERROR_LIST_ASSETS";

export const START_HISTORY_ASSET = "[APPROVED] START_HISTORY_ASSET";
export const SUCCESS_HISTORY_ASSET = "[APPROVED] SUCCESS_HISTORY_ASSET";
export const ERROR_HISTORY_ASSET = "[APPROVED] ERROR_HISTORY_ASSET";

export const START_DATA_EMPLOYEE = "[APPROVED] START_DATA_EMPLOYEE";
export const SUCCESS_DATA_EMPLOYEE = "[APPROVED] SUCCESS_DATA_EMPLOYEE";
export const ERROR_DATA_EMPLOYEE = "[APPROVED] ERROR_DATA_EMPLOYEE";
