/** COMMON */
export const CHANGE_LANGUAGE = "[COMMON] CHANGE_LANGUAGE";
/** MASRER DATA */
export const START_MASTER_GET_ALL = "[MASTER] START_MASTER_GET_ALL";
export const SUCCESS_MASTER_GET_ALL = "[MASTER] SUCCESS_MASTER_GET_ALL";
export const ERROR_MASTER_GET_ALL = "[MASTER] ERROR_MASTER_GET_ALL";

export const UPDATE_MASTER_SUPPLIER = "[MASTER] UPDATE_MASTER_SUPPLIER";
/** REFRESH TOKEN */
export const START_REFRESH_TOKEN = "[AUTH] START_REFRESH_TOKEN";
export const SUCCESS_REFRESH_TOKEN = "[AUTH] SUCCESS_REFRESH_TOKEN";
export const ERROR_REFRESH_TOKEN = "[AUTH] ERROR_REFRESH_TOKEN";
/** SIGN OUT */
export const SIGN_OUT = "[AUTH] SIGN_OUT";
/** SIGN IN */
export const START_SIGN_IN = "[AUTH] START_SIGN_IN";
export const SUCCESS_SIGN_IN = "[AUTH] SUCCESS_SIGN_IN";
export const ERROR_SIGN_IN = "[AUTH] ERROR_SIGN_IN";
/** FORGOT PASSWORD */
export const RESET_FORGOT_PASSWORD = "[AUTH] RESET_FORGOT_PASSWORD";
export const START_FORGOT_PASSWORD = "[AUTH] START_FORGOT_PASSWORD";
export const SUCCESS_FORGOT_PASSWORD = "[AUTH] SUCCESS_FORGOT_PASSWORD";
export const ERROR_FORGOT_PASSWORD = "[AUTH] ERROR_FORGOT_PASSWORD";
/** RESET PASSWORD */
export const RESET_RESET_PASSWORD = "[AUTH] RESET_RESET_PASSWORD";
export const START_TOKEN_PASSWORD = "[AUTH] START_TOKEN_PASSWORD";
export const SUCCESS_TOKEN_PASSWORD = "[AUTH] SUCCESS_TOKEN_PASSWORD";
export const ERROR_TOKEN_PASSWORD = "[AUTH] ERROR_TOKEN_PASSWORD";
export const START_RESET_PASSWORD = "[AUTH] START_RESET_PASSWORD";
export const SUCCESS_RESET_PASSWORD = "[AUTH] SUCCESS_RESET_PASSWORD";
export const ERROR_RESET_PASSWORD = "[AUTH] ERROR_RESET_PASSWORD";
/** APPROVED - ASSETS */
export const START_LIST_ASSETS = "[APPROVED] START_LIST_ASSETS";
export const SUCCESS_LIST_ASSETS = "[APPROVED] SUCCESS_LIST_ASSETS";
export const ERROR_LIST_ASSETS = "[APPROVED] ERROR_LIST_ASSETS";

export const START_HISTORY_ASSET = "[APPROVED] START_HISTORY_ASSET";
export const SUCCESS_HISTORY_ASSET = "[APPROVED] SUCCESS_HISTORY_ASSET";
export const ERROR_HISTORY_ASSET = "[APPROVED] ERROR_HISTORY_ASSET";

export const START_DATA_EMPLOYEE = "[APPROVED] START_DATA_EMPLOYEE";
export const SUCCESS_DATA_EMPLOYEE = "[APPROVED] SUCCESS_DATA_EMPLOYEE";
export const ERROR_DATA_EMPLOYEE = "[APPROVED] ERROR_DATA_EMPLOYEE";

export const RESET_CREATE_ASSETS = "[APPROVED] RESET_CREATE_ASSETS";

export const START_CREATE_ASSETS = "[APPROVED] START_CREATE_ASSETS";
export const SUCCESS_CREATE_ASSETS = "[APPROVED] SUCCESS_CREATE_ASSETS";
export const ERROR_CREATE_ASSETS = "[APPROVED] ERROR_CREATE_ASSETS";

export const START_UPDATE_ASSETS = "[APPROVED] START_UPDATE_ASSETS";
export const SUCCESS_UPDATE_ASSETS = "[APPROVED] SUCCESS_UPDATE_ASSETS";
export const ERROR_UPDATE_ASSETS = "[APPROVED] ERROR_UPDATE_ASSETS";

export const START_APPROVED_RECALL_ASSETS = "[APPROVED] START_APPROVED_RECALL_ASSETS";
export const SUCCESS_APPROVED_RECALL_ASSETS = "[APPROVED] SUCCESS_APPROVED_RECALL_ASSETS";
export const ERROR_APPROVED_RECALL_ASSETS = "[APPROVED] ERROR_APPROVED_RECALL_ASSETS";

export const START_REPAIR_ASSETS = "[APPROVED] START_REPAIR_ASSETS";
export const SUCCESS_REPAIR_ASSETS = "[APPROVED] SUCCESS_REPAIR_ASSETS";
export const ERROR_REPAIR_ASSETS = "[APPROVED] ERROR_REPAIR_ASSETS";

export const START_LIQUIDATION_ASSETS = "[APPROVED] START_LIQUIDATION_ASSETS";
export const SUCCESS_LIQUIDATION_ASSETS = "[APPROVED] SUCCESS_LIQUIDATION_ASSETS";
export const ERROR_LIQUIDATION_ASSETS = "[APPROVED] ERROR_LIQUIDATION_ASSETS";

export const START_REUSE_ASSETS = "[APPROVED] START_REUSE_ASSETS";
export const SUCCESS_REUSE_ASSETS = "[APPROVED] SUCCESS_REUSE_ASSETS";
export const ERROR_REUSE_ASSETS = "[APPROVED] ERROR_REUSE_ASSETS";

export const START_CREATE_SUPPLIER = "[APPROVED] START_CREATE_SUPPLIER";
export const SUCCESS_CREATE_SUPPLIER = "[APPROVED] SUCCESS_CREATE_SUPPLIER";
export const ERROR_CREATE_SUPPLIER = "[APPROVED] ERROR_CREATE_SUPPLIER";

export const START_UPDATE_PROCESS = "[APPROVED] START_UPDATE_PROCESS";
export const SUCCESS_UPDATE_PROCESS = "[APPROVED] SUCCESS_UPDATE_PROCESS";
export const ERROR_UPDATE_PROCESS = "[APPROVED] ERROR_UPDATE_PROCESS";

export const START_LIST_REQUEST_HANDLE = "[APPROVED] START_LIST_REQUEST_HANDLE";
export const SUCCESS_LIST_REQUEST_HANDLE = "[APPROVED] SUCCESS_LIST_REQUEST_HANDLE";
export const ERROR_LIST_REQUEST_HANDLE = "[APPROVED] ERROR_LIST_REQUEST_HANDLE";

export const RESET_APPROVED_REQUEST = "[APPROVED] RESET_APPROVED_REQUEST";

export const START_APPROVED_REQUEST = "[APPROVED] START_APPROVED_REQUEST";
export const SUCCESS_APPROVED_REQUEST = "[APPROVED] SUCCESS_APPROVED_REQUEST";
export const ERROR_APPROVED_REQUEST = "[APPROVED] ERROR_APPROVED_REQUEST";