/** COMMON */
export const CHANGE_LANGUAGE = "[COMMON] CHANGE_LANGUAGE";
/** REFRESH TOKEN */
export const REFRESH_TOKEN = "[AUTH] REFRESH_TOKEN";
/** SIGN OUT */
export const SIGN_OUT = "[AUTH] SIGN_OUT";
/** SIGN IN */
export const START_SIGN_IN = "[AUTH] START_SIGN_IN";
export const SUCCESS_SIGN_IN = "[AUTH] SUCCESS_SIGN_IN";
export const ERROR_SIGN_IN = "[AUTH] ERROR_SIGN_IN";
/** FORGOT PASSWORD */
export const RESET_FORGOT_PASSWORD = "[AUTH] RESET_FORGOT_PASSWORD";
export const START_FORGOT_PASSWORD = "[AUTH] START_FORGOT_PASSWORD";
export const SUCCESS_FORGOT_PASSWORD = "[AUTH] SUCCESS_FORGOT_PASSWORD";
export const ERROR_FORGOT_PASSWORD = "[AUTH] ERROR_FORGOT_PASSWORD";
/** RESET PASSWORD */
export const RESET_RESET_PASSWORD = "[AUTH] RESET_RESET_PASSWORD";
export const START_TOKEN_PASSWORD = "[AUTH] START_TOKEN_PASSWORD";
export const SUCCESS_TOKEN_PASSWORD = "[AUTH] SUCCESS_TOKEN_PASSWORD";
export const ERROR_TOKEN_PASSWORD = "[AUTH] ERROR_TOKEN_PASSWORD";
export const START_RESET_PASSWORD = "[AUTH] START_RESET_PASSWORD";
export const SUCCESS_RESET_PASSWORD = "[AUTH] SUCCESS_RESET_PASSWORD";
export const ERROR_RESET_PASSWORD = "[AUTH] ERROR_RESET_PASSWORD";